### Week2 Pandas

In [2]:
import pandas as pd
import numpy as np

##### pandas.Series

In [8]:
sr = pd.Series(np.random.randn(10), index = list('abcdefghij'))
sr

a    2.133856
b   -1.777709
c   -0.776784
d   -0.951830
e   -0.187814
f   -0.595315
g    1.694050
h    0.044629
i   -0.954038
j    0.434577
dtype: float64

In [9]:
type(sr)

pandas.core.series.Series

In [11]:
print(f'''
Series.type 
:{type(sr)}

Series.index
:{sr.index}

Series.index[2]
:{sr.index[2]}

Series.values
:{sr.values}


Series[sr.index[2]]
:{sr[sr.index[2]]}

''')


Series.type 
:<class 'pandas.core.series.Series'>

Series.index
:Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

Series.index[2]
:c

Series.values
:[ 2.13385641 -1.77770868 -0.77678442 -0.95183029 -0.1878141  -0.59531535
  1.69405002  0.04462935 -0.95403838  0.43457664]


Series[sr.index[2]]
:-0.7767844247374543




In [12]:
li = ['291032', 3.34, 'df', True, 19]
pd.Series(li)

0    291032
1      3.34
2        df
3      True
4        19
dtype: object

##### pandas.DataFrame

In [15]:
df = pd.DataFrame(np.array(np.random.randn(20)).reshape(4,5),
                 columns = list('ABCDE'))
df

A         B         C         D         E
0  0.169560  0.875891  3.542626 -2.034773  0.797755
1 -0.805976  0.890172 -0.329776 -0.093916 -0.240540
2 -0.067726  0.827684 -0.491403  0.129598 -1.185854
3 -1.032956 -0.539257  0.062250  0.799433  1.017169

In [17]:
print(f'''
DataFrame.type 
:{type(df)}

DataFrame.index
:{df.index}

DataFrame.index[2]
:{df.index[2]}

DataFrame.columns
:{df.columns}

DataFrame.values
:{df.values}


Series[sr.index[2]]
:{sr[sr.index[2]]}

''')


DataFrame.type 
:<class 'pandas.core.frame.DataFrame'>

DataFrame.index
:RangeIndex(start=0, stop=4, step=1)

DataFrame.index[2]
:2

DataFrame.columns
:Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

DataFrame.values
:[[ 0.16955991  0.87589068  3.54262627 -2.03477321  0.79775496]
 [-0.80597578  0.89017169 -0.32977643 -0.09391564 -0.24053969]
 [-0.06772644  0.82768431 -0.49140301  0.12959768 -1.18585389]
 [-1.03295569 -0.53925661  0.06225029  0.79943313  1.01716942]]


Series[sr.index[2]]
:-0.7767844247374543




drop row/ column in df

In [20]:
df.drop(0)

A         B         C         D         E
1 -0.805976  0.890172 -0.329776 -0.093916 -0.240540
2 -0.067726  0.827684 -0.491403  0.129598 -1.185854
3 -1.032956 -0.539257  0.062250  0.799433  1.017169

In [21]:
df.drop('A', axis = 1)

B         C         D         E
0  0.875891  3.542626 -2.034773  0.797755
1  0.890172 -0.329776 -0.093916 -0.240540
2  0.827684 -0.491403  0.129598 -1.185854
3 -0.539257  0.062250  0.799433  1.017169

indexing row/ column in df

In [25]:
df.index = range(1,5)
df.loc[2:]

A         B         C         D         E
2 -0.805976  0.890172 -0.329776 -0.093916 -0.240540
3 -0.067726  0.827684 -0.491403  0.129598 -1.185854
4 -1.032956 -0.539257  0.062250  0.799433  1.017169

In [26]:
df.iloc[2:]

A         B         C         D         E
3 -0.067726  0.827684 -0.491403  0.129598 -1.185854
4 -1.032956 -0.539257  0.062250  0.799433  1.017169

In [27]:
df.loc[2:,['A',"C"]]

A         C
2 -0.805976 -0.329776
3 -0.067726 -0.491403
4 -1.032956  0.062250

In [28]:
df.iloc[2:,2:]

C         D         E
3 -0.491403  0.129598 -1.185854
4  0.062250  0.799433  1.017169

In [29]:
df.loc[5] = np.random.randn(5)
df

A         B         C         D         E
1  0.169560  0.875891  3.542626 -2.034773  0.797755
2 -0.805976  0.890172 -0.329776 -0.093916 -0.240540
3 -0.067726  0.827684 -0.491403  0.129598 -1.185854
4 -1.032956 -0.539257  0.062250  0.799433  1.017169
5 -0.480029 -0.116508 -0.870467  0.484898 -0.390914

setting index in df

In [30]:
df.set_index('A')

B         C         D         E
A                                                
 0.169560  0.875891  3.542626 -2.034773  0.797755
-0.805976  0.890172 -0.329776 -0.093916 -0.240540
-0.067726  0.827684 -0.491403  0.129598 -1.185854
-1.032956 -0.539257  0.062250  0.799433  1.017169
-0.480029 -0.116508 -0.870467  0.484898 -0.390914

In [35]:
df.reindex([2,3,1,4,5])

A         B         C         D         E
2 -0.805976  0.890172 -0.329776 -0.093916 -0.240540
3 -0.067726  0.827684 -0.491403  0.129598 -1.185854
1  0.169560  0.875891  3.542626 -2.034773  0.797755
4 -1.032956 -0.539257  0.062250  0.799433  1.017169
5 -0.480029 -0.116508 -0.870467  0.484898 -0.390914

In [36]:
df.reset_index()

index         A         B         C         D         E
0      1  0.169560  0.875891  3.542626 -2.034773  0.797755
1      2 -0.805976  0.890172 -0.329776 -0.093916 -0.240540
2      3 -0.067726  0.827684 -0.491403  0.129598 -1.185854
3      4 -1.032956 -0.539257  0.062250  0.799433  1.017169
4      5 -0.480029 -0.116508 -0.870467  0.484898 -0.390914

In [ ]:
df.sort_index()